routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('classes', 'ClassController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'email', 'password', 'account_type',
    ];

    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;

    }// end of getFullNameAttribute

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    //scopes
    public function scopeWhenAccountType($query, $accountType)
    {
        return $query->when($accountType, function ($q) use ($accountType) {

            return $q->where('account_type', $accountType);

        });

    }// end of scopeWhenAccountType

}//end of model

resources/views/admin/courses/create.blade.php
@extends('layouts.admin.app')

@section('content')

    <h2 class="mb-2">@lang('courses.courses')</h2>

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-gray-light">
            <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ route('admin.courses.index') }}">@lang('courses.courses')</a></li>
            <li class="breadcrumb-item active" aria-current="page">@lang('site.create')</li>
        </ol>
    </nav>

    <div class="row">

        <div class="col-md-12">

            <div class="block">

                <div class="block-content block-content-full">

                    @include('admin.partials._errors')

                    <form action="{{ route('admin.courses.store') }}" method="post">
                        @csrf
                        @method('post')

                        {{--name--}}
                        <div class="form-group">
                            <label>@lang('courses.name')</label>
                            <input type="text" name="name" class="form-control" autofocus value="{{ old('name') }}">
                        </div>

                        {{--teacher_id--}}
                        <div class="form-group">
                            <label>@lang('users.teacher')</label>
                            <select name="teacher_id" class="form-control select2">
                                <option value="">@lang('site.choose') @lang('users.teacher')</option>
                                @foreach ($teachers as $teacher)
                                    <option value="{{ $teacher->id }}" {{ $teacher->id == old('teacher_id') ? 'selected' : '' }}>{{ $teacher->full_name }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary"><i class="fa fa-plus"></i> @lang('site.add')</button>
                        </div>

                    </form><!-- end of form -->

                </div><!-- end of block content -->

            </div><!-- end of block-->

        </div><!-- end of col -->

    </div><!-- end of row -->

@endsection

resources/views/admin/courses/edit.blade.php
@extends('layouts.admin.app')

@section('content')

    <h2 class="mb-2">@lang('courses.courses')</h2>

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-gray-light">
            <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ route('admin.courses.index') }}">@lang('courses.courses')</a></li>
            <li class="breadcrumb-item active" aria-current="page">@lang('site.edit')</li>
        </ol>
    </nav>

    <div class="row">

        <div class="col-md-12">

            <div class="block">

                <div class="block-content block-content-full">

                    @include('admin.partials._errors')

                    <form method="post" action="{{ route('admin.courses.update', $course->id) }}">
                        @csrf
                        @method('put')

                        {{--name--}}
                        <div class="form-group">
                            <label>@lang('courses.name')</label>
                            <input type="text" name="name" class="form-control" autofocus value="{{ old('name', $course->name) }}">
                        </div>

                        {{--teacher_id--}}
                        <div class="form-group">
                            <label>@lang('users.teacher')</label>
                            <select name="teacher_id" class="form-control select2">
                                <option value="">@lang('site.choose') @lang('users.teacher')</option>
                                @foreach ($teachers as $teacher)
                                    <option value="{{ $teacher->id }}" {{ $teacher->id == $course->teacher_id ? 'selected' : '' }}>{{ $teacher->full_name }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary"><i class="fa fa-edit"></i>@lang('site.edit')</button>
                        </div>

                    </form><!-- end of form -->

                </div><!-- end of block content -->

            </div><!-- end of tile -->

        </div><!-- end of col -->

    </div><!-- end of row -->

@endsection

resources/views/admin/courses/index.blade.php
@extends('layouts.admin.app')

@section('content')

    <h2 class="mb-2">@lang('courses.courses')</h2>

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-gray-light">
            <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">@lang('site.home')</a></li>
            <li class="breadcrumb-item active" aria-current="page">@lang('courses.courses')</li>
        </ol>
    </nav>

    <div class="row">

        <div class="col-md-12">

            <div class="block">

                <div class="block-content block-content-full">

                    <div class="row mb-2">

                        <div class="col-md-12">
                            @if (auth()->user()->hasPermission('create_courses'))
                                <a href="{{ route('admin.courses.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> @lang('site.add')</a>
                            @endif
                            @if (auth()->user()->hasPermission('delete_courses'))
                                <form method="post" action="{{ route('admin.courses.bulk_delete') }}" style="display: inline-block;">
                                    @csrf
                                    @method('delete')
                                    <input type="hidden" name="record_ids" id="record-ids">
                                    <button type="submit" class="btn btn-danger" id="bulk-delete" disabled="true"><i class="fa fa-trash"></i> @lang('site.bulk_delete')</button>
                                </form><!-- end of form -->
                            @endif
                        </div>

                    </div><!-- end of row -->

                    <div class="row">

                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="text" id="data-table-search" class="form-control" autofocus placeholder="@lang('site.search')">
                            </div>
                        </div>

                    </div><!-- end of row -->

                    <div class="row">

                        <div class="col-md-12 table-responsive">
                            <table class="table" id="courses-table" style="width: 100%;">
                                <thead>
                                <tr>
                                    <th>
                                        <label class="css-control css-control-primary css-checkbox">
                                            <input type="checkbox" class="css-control-input" id="record__select-all">
                                            <span class="css-control-indicator"></span>
                                        </label>
                                    </th>
                                    <th>@lang('courses.name')</th>
                                    <th>@lang('users.teacher')</th>
                                    <th>@lang('site.created_at')</th>
                                    <th>@lang('site.action')</th>
                                </tr>
                                </thead>
                            </table>
                        </div>

                    </div><!-- end of row -->

                </div><!-- end of block content -->

            </div><!-- end of block-->

        </div><!-- end of col -->

    </div><!-- end of row -->

@endsection

@push('scripts')

    <script>

        let coursesTable = $('#courses-table').DataTable({
            dom: "tiplr",
            serverSide: true,
            processing: true,
            ajax: {
                url: '{{ route('admin.courses.data') }}',
            },
            columns: [
                {data: 'record_select', name: 'record_select', searchable: false, sortable: false, width: '1%'},
                {data: 'name', name: 'name'},
                {data: 'teacher', name: 'teacher'},
                {data: 'created_at', name: 'created_at', searchable: false},
                {data: 'actions', name: 'actions', searchable: false, sortable: false},
            ],
            order: [[1, 'asc']],
            drawCallback: function (settings) {
                $('.record__select').prop('checked', false);
                $('#record__select-all').prop('checked', false);
                $('#record-ids').val();
                $('#bulk-delete').attr('disabled', true);

            }
        });

        $('#data-table-search').keyup(function () {
            coursesTable.search(this.value).draw();
        })
    </script>

@endpush